### ISSUE TITLE
Cannot Initialize Health Kit, initHealthkit undefined

### ISSUE THREAD

**Issue by blakete** [agencyenterprise/react-native-health#104]
**Describe the bug**
When running example code from the readme I am left with the error: 
```js
TypeError: undefined is not a function (near '..._reactNativeHealth.default.initHealthKit...')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**To Reproduce**

1. ``` expo init AwesomeProject ```
2. Choose minimal typescript template
3. edit /AwesomeProject/App.tsx 
```js
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import AppleHealthKit, {
  HealthValue,
  HealthKitPermissions,
} from 'react-native-health'

/* Permission options */
const permissions = {
  permissions: {
    read: [AppleHealthKit.Constants.Permissions.HeartRate],
    write: [AppleHealthKit.Constants.Permissions.Steps],
  },
} as HealthKitPermissions

console.log("initializing health kit")
AppleHealthKit.initHealthKit(permissions, (error: string) => {
  /* Called after we receive a response from the system */

  if (error) {
    console.log('[ERROR] Cannot grant permissions!')
  }

  /* Can now read or write to HealthKit */

  const options = {
    startDate: new Date(2020, 1, 1).toISOString(),
  }

  AppleHealthKit.getHeartRateSamples(
    options,
    (callbackError: string, results: HealthValue[]) => {
      /* Samples are now collected from HealthKit */
    },
  )
})


import useCachedResources from './hooks/useCachedResources';
import useColorScheme from './hooks/useColorScheme';
import Navigation from './navigation';

export default function App() {

  
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();

  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <SafeAreaProvider>
        <Navigation colorScheme={colorScheme} />
        <StatusBar />
      </SafeAreaProvider>
    );
  }
}
```
2. ``` cd AwesomeProject ```
3. ``` npm start ```
4. When opening on Expo app on iPhone this error is presented in terminal.

**Expected behavior**
Expected the Health Kit to initialize, request permissions, and access the heart rate data.

**Screenshots**
![Screenshot 2021-05-23 at 10 12 05 PM](https://user-images.githubusercontent.com/49415344/119287176-f114ba00-bc13-11eb-926e-63954ebdd5fb.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS: iOS 14.5.1

**Comment by eveningkid** [comment]
Hey Blake,

Seems like you're trying this in Expo Go although the module isn't supported by the Expo SDK.

You'll need to either:
- Use it in a bare React Native/Expo (not managed) project
- Create a custom runtime using Expo development clients

**Comment by EvanBacon** [comment]
Docs: https://github.com/agencyenterprise/react-native-health/blob/master/docs/Expo.md

**Comment by blakete** [comment]
@EvanBacon thank you! It worked when implementing in a bare project.
